### PR TITLE
v1.0 release thread

### PR DESCRIPTION
**Pull request by xamgore**
Ok, my head is spinning, I suggest we all have the single place to discuss the following updates.

- @bunny-therapist have aligned python & rust implementations, forked the repo and fixed a few things
- @xamgore merged all those fixes into his fork, but have got different scores for 'google' text
- #16 issue is the last one

### CODE REVIEW

**Comment by bunny-therapist** [comment]
Ok, let's keep the discussion here then.

I should maybe clarify that the big "google" test I have in my branch does NOT pass. The other tests pass. I have just aligned the expected test result with the official "Yake!" webpage (using the LIAAD/yake implementation) results, because that is the goal.

I currently believe that if we handle the plural issue, then it is possible that we will match LIAAD/yake.

**Comment by bunny-therapist** [comment]
Closes #10 
Closes #8

**Comment by bunny-therapist** [comment]
To me, it seems like what LIAAD/yake does [here](https://github.com/LIAAD/yake/blob/master/yake/datarepresentation.py#L148) is to *when building the vocabulary* check if the word has length > 3 and ends with an "s", and if so, the "s" is dropped (last character of word is not used). I tried to add something like that to `vocabulary_building` but I don't know how to do that without the rust compiler getting mad at me.

**Comment by bunny-therapist** [comment]
I suppose something like this? (I got it working in [Rust Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021) at least.)
```
fn main() {
    let word = "competitors";
    
    let mut actual_word: &str = word;
    if word.len() > 3 && word.ends_with("s") {
        actual_word = &word[0..word.len() - 1];
    }
    println!("{}", actual_word);
}
```
outputs "competitor".

Can we just use something like this in the `vocabulary_building` loop?

**Comment by xamgore** [comment]
```rust
let mut word = ...;

if word.ends_with('_') {
    word.pop();
}
```

**Comment by bunny-therapist** [comment]
After dinner maybe :)

I am not entirely sure about "vocabulary" vs sentences vs candidates etc. I assume that what we want is to treat "competitors" as "competitor" etc, at least to a point.

**Comment by xamgore** [comment]
Ok, let vocabulary be a map from _s-less_ words into occurrences. 

```rust
for (w_idx, word) in sentence.words.iter().enumerate() {
    if !word.is_empty()
        && word.chars().all(char::is_alphanumeric)
        && HashSet::from_iter(word.chars()).intersection(&self.config.punctuation).next().is_none()
    {
        let mut index = word.to_lowercase();

        // normalize the plural form
        if index.ends_with('s') {
            index.pop();
        }

        let occurrence = Occurrence { shift_offset: shift + w_idx, idx, word, shift };
        words.entry(index).or_default().push(occurrence)
    }
}
```

**Comment by quesurifn** [comment]
Pointing this to 1.0.0-alpha branch to get all of these changes production ready

**Comment by xamgore** [comment]
Well, thanks, but it still WIP 😄

**Comment by quesurifn** [comment]
Shit.

**Pull request merged**
