### PR TITLE
Add parenthesis to score expression

### LINKED ISSUE #10: Likely bug in score normalization
It looks like the normalization is wrong for the score.

If you look in the [YAKE paper](https://repositorio.inesctec.pt/server/api/core/bitstreams/ef121a01-a0a6-4be8-945d-3324a58fc944/content), eq. (1), the score should be the S-product divided by (TF + S-sum), but when we look in the code:
https://github.com/quesurifn/yake-rust/blob/master/yake_rust/src/lib.rs#L364
we see
```
 let weight = prod_ / tf * (1.0 + sum_);
```
Shouldn't this be
```
 let weight = prod_ / (tf * (1.0 + sum_));
```
?
The way it is now, we divide by tf but then multiply the whole thing by `(1.0 + sum_)`. From the paper (and other implementations), it looks like all of that should be in the denominator?

### PR DESCRIPTION
**Pull request by bunny-therapist**
Closes #10

### CODE REVIEW

**Comment by quesurifn** [comment]
@bunny-therapist Do you mind checking against the sample on their website? 

http://yake.inesctec.pt/demo.html?doc=Sample1#

**Comment by quesurifn** [comment]
You are right about there being a mathematical issue though. Their scores have one as the highest score.  The scores in this repo are basically the opposite. The lower the score the better.

**Comment by quesurifn** [comment]
@bunny-therapist Do you have a discord we can discuss this on? I'm looking at this. The scores look better with this version but the actual results seem slightly worse. There seems to be an increase of results with adjectives and I don't think that's what we want.

**Comment by bunny-therapist** [comment]
I am running it against their sample, but I am not getting the same results with either this PR or the pre-existing yake-rust code.

I am trying to create python binding for yake-rust so we can replace LIAAD/yake in our projects. For this reason, I am running tests comparing the yake-rust results to LIAAD/yake - that is how I am finding these issues.

Even with this PR, I am not getting the same as LIAAD/yake nor the homepage. However, I believe that is because there are more issues here. I think this PR fixes one issue, but I still think there are issues related to relatedness and frequency (when I am comparing LIAAD/yake and yake-rust, the discrepancies appear to be coming from those two).

**Comment by bunny-therapist** [comment]
I am pretty sure this is also a bug: https://github.com/quesurifn/yake-rust/issues/12

But I think there may be more.

**Comment by bunny-therapist** [comment]
Do we expect agreement with the yake homepage? Because in that case we should just use their scores for the tests in the future.

**Comment by bunny-therapist** [comment]
> @bunny-therapist Do you have a discord we can discuss this on? I'm looking at this. The scores look better with this version but the actual results seem slightly worse. There seems to be an increase of results with adjectives and I don't think that's what we want.
> 
> I'm thinking this could be a scenario where the fix you've posted is uncovering a deficiency somewhere else but I'm not sure.

No I do not have a discord. I have only used the discords of others to discuss their projects. I am not a very experienced discord user.

**Comment by bunny-therapist** [comment]
If I do the changes from #12 together with these changes, we get
```
        let results: Results = vec![
            ResultItem { raw: "data science".to_owned(), keyword: "data science".to_owned(), score: 0.0599 },
            ResultItem { raw: "Google Cloud Platform".to_owned(), keyword: "google cloud platform".to_owned(), score: 0.0656 },
            ResultItem { raw: "acquiring data science".to_owned(), keyword: "acquiring data science".to_owned(), score: 0.0735 },
            ResultItem { raw: "science community Kaggle".to_owned(), keyword: "science community kaggle".to_owned(), score: 0.0804 },
            ResultItem { raw: "acquiring Kaggle".to_owned(), keyword: "acquiring kaggle".to_owned(), score: 0.0924 },
            ResultItem { raw: "CEO Anthony Goldbloom".to_owned(), keyword: "ceo anthony goldbloom".to_owned(), score: 0.096 },
            ResultItem { raw: "Google Cloud".to_owned(), keyword: "google cloud".to_owned(), score: 0.1085 },
            ResultItem { raw: "Kaggle".to_owned(), keyword: "kaggle".to_owned(), score: 0.1178 },
            ResultItem { raw: "Google".to_owned(), keyword: "google".to_owned(), score: 0.1357 },
            ResultItem { raw: "machine learning".to_owned(), keyword: "machine learning".to_owned(), score: 0.1513 },
        ];
```

**Comment by quesurifn** [comment]
@bunny-therapist I can't. I'm going based on what I'd expect so not objective by any measure. For me though the `science community kaggle` and `acquiring kaggle` results shouldn't be in that top 10 list. Everything else looks okay. 

When I originally released this I remember noticing the issue but thinking the results were close enough. 

To answer your question, yes I think we should shoot for their scores.

**Comment by quesurifn** [comment]
I think the play here is to branch off of main, maybe create a "v1.0.0" branch to work towards 1:1 scores with that. That way if we start going the wrong direction we can easily just keep whats in main because I think it works well enough if we can't get to 1:1 scoring.

**Comment by bunny-therapist** [comment]
To work toward their scores, that sounds like a good idea. But we are merging this and looking into the other bug, right?
Or do you mean to do that as part of that branch?

**Comment by quesurifn** [comment]
@bunny-therapist I'll create a v1.0.0-alpha branch and release this as that.

**Comment by bunny-therapist** [comment]
I can post more about the other bugs I reported and what scores we get tomorrow. I have to stop for today since it is getting late here.

**Comment by quesurifn** [comment]
Thanks for your help. I'll release this today sometime.

**Pull request merged**
